### ISSUE TITLE
Pokémon

### ISSUE THREAD

**Issue by 0w0u** [0w0u/noa#14]
Esteban por favor arregla en [esta línea](https://github.com/wwmon/noa/blob/master/commands/Diversi%C3%B3n/pok%C3%A9mon.js#L30) algo, ponle esto; `attempts.content.toLowerCase() === pokem.name.toLowerCase()`

**Comment by estebanDT30** [comment]
**Hecho.**
1ea36dbb9faf46e8601ec82c1c2a19ad22ec86fc
